language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - MAGENTO_VERSION=magento-mirror-1.9.3.6
  - MAGENTO_VERSION=magento-mirror-1.9.2.4
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.8.0.0


before_script:
  - export PATH=$PATH:$HOME/.composer/vendor/bin
  - if find . -name "*.php" -print0 | xargs -0 -n 1 -P 8 php -l | grep -v "No syntax errors detected"; then exit 1; fi

script:
  - bash setup.sh

cache:
  directories:
  - $HOME/.composer
